# The configurations you want to execute
# That is, a combination of operating system and python version
# Please add or remove for your needs.
# Check all possible values for python in here: https://docs.travis-ci.com/user/languages/python/
# See how to further configure the matrix of combinations in here: https://docs.travis-ci.com/user/multi-os/
matrix:
    include:
        - os: linux
          python: 3.2
        - os: linux
          python: 3.3
        - os: osx
          language: generic
          env: TOXENV=py32
        - os: osx
          language: generic
          env: TOXENV=py33

# Command to install dependencies for each configuration.
install:
# For OSX, you may want to call a script installing virtual env and so on.
  - pip install .
  
# Command to run tests. These are run for each configuration
script: pytest